// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package dev.bengi.interfaceservice;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dev_bengi_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dev_bengi_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dev_bengi_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dev_bengi_MessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\tdev.bengi\"!\n\016MessageReq" +
      "uest\022\017\n\007message\030\001 \001(\t\"\"\n\017MessageResponse" +
      "\022\017\n\007message\030\001 \001(\t2U\n\016MessageService\022C\n\ng" +
      "etMessage\022\031.dev.bengi.MessageRequest\032\032.d" +
      "ev.bengi.MessageResponseB,\n\032dev.bengi.in" +
      "terfaceserviceB\014MessageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dev_bengi_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dev_bengi_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dev_bengi_MessageRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_dev_bengi_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dev_bengi_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dev_bengi_MessageResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
