// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package dev.bengi.interfaceservice;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dev.bengi.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The message field of type string
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * The message field of type string
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
